disabled_rules: # rule identifiers to exclude from running
  - line_length
  - identifier_name
  - block_based_kvo

included: # paths to include during linting. `--path` is ignored if present.
  - NewsApp
  - NewsAppTests
